import type { Metadata } from "next"
import { Header } from "../components/common/header"
import { Footer } from "@/components/common/footer"
import "./globals.css"

export const metadata: Metadata = {
  title: "MacBook Pro - Apple (BR)",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
